language: haxe

haxe:
  - "3.2.0"
  - development

env:
  - TEST=cpp.run.hxml
  - TEST=cs.run.hxml
  - TEST=java.run.hxml
  - TEST=js.run.hxml
  - TEST=php.run.hxml
  - TEST=neko.run.hxml
  - TEST=python.run.hxml
  global:
    - CI_NODE_TOTAL=2
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1

addons:
  apt:
    packages:
      - python3
      - php5-cli
      - mono-devel
      - mono-mcs
      - nodejs

before_install:
  - source hxml/haxe_travis_scripts/scripts.sh

install:
  - install_hxcpp
  - install_hxjava
  - install_hxcs
  - haxelib install utest
  - haxelib list

script:
  - haxe "hxml/$TEST" -D travis
