language: haxe

haxe:
  - "3.1.3"
  - development

env:
  global:
    - secure: UUVsPXSN6eOaKoUaTbGuK7OeaglIkkvNqkkZgR5ZttJ/d8hkRLDVD6rJntL/clHTOvpwxINCesa+sp8t4fFJuCA4PWrQg2cBrkx1FcmgzurQhsSoiqVUfWn56wzvHCVW7GhieLpINSEFZXMG1qt7RbsOHcs15SImJ2V+ik91zuE=
    - secure: GtWMwFaNAmEq+ubx28jg32N40mIPAm5tTxD5TJlF5eFONpnVNV78p/E2CeHSgpMqrAiRTAyT/4KrjimIRs0XB6R5aW470/DHTgercwTzP+SzcHjqDm6fHnkiqemH9f+xS/JZvc1xs/2KoVm8uLokBrIJBSuW21yy+BrEhnBECUo=

addons:
  apt:
    packages:
      #- python3
      #- php5-cli
      #- mono-devel
      #- mono-mcs
      - nodejs

install:
  - if [[ $TRAVIS_HAXE_VERSION == "development" ]]; then haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git fi
  - if [[ $TRAVIS_HAXE_VERSION == "3.1.3" ]]; then haxelib install hxcpp:3.1.3 fi
  - if [[ $TRAVIS_HAXE_VERSION == "development" ]]; then haxelib git hxjava https://github.com/HaxeFoundation/hxjava.git fi
  - if [[ $TRAVIS_HAXE_VERSION == "3.1.3" ]]; then haxelib install hxjava:3.1.3 fi
  #- if [[ $TRAVIS_HAXE_VERSION == "development" ]]; then haxelib git hxcs https://github.com/HaxeFoundation/hxcs.git fi
  #- if [[ $TRAVIS_HAXE_VERSION == "3.1.3" ]]; then haxelib install hxcs:3.1.3 fi
  - haxelib install utest
  - haxelib list

script:
  - haxe hxml/cpp.hxml && ./bin/cpp/TestAll
  #- haxe hxml/cs.hxml && mono bin/cs/bin/TestAll.exe
  #- haxe hxml/flash.hxml # TODO
  - haxe hxml/java.hxml && java -jar bin/java/TestAll.jar
  #- haxe hxml/js.hxml # TODO + saucelabs
  - haxe hxml/js.hxml && node bin/js.js
  #- haxe hxml/php.hxml && php bin/php/index.php
  - haxe hxml/neko.hxml && neko bin/neko.n
  #- haxe hxml/python.hxml && python3 bin/python.py
