language: haxe

haxe:
  - "3.2.0"
  - development

env:
  matrix:
    - TEST=cpp
    - TEST=cs
    - TEST=java
    - TEST=js
    - TEST=php
    - TEST=neko
    - TEST=python

addons:
  apt:
    packages:
      - python3
      - php5-cli
      - mono-devel
      - mono-mcs
      - nodejs

before_install:
  - source hxml/haxe_travis_scripts/scripts.sh

install:
  - if [[ $TEST == "cpp" ]]; then install_hxcpp; fi
  - if [[ $TEST == "java" ]]; then install_hxjava; fi
  - if [[ $TEST == "cs" ]]; then install_hxcs; fi
  - haxelib install utest

script:
  - haxe "hxml/$TEST.run.hxml" -D travis
