language: haxe

haxe:
  - "3.2.0"
  - development

addons:
  apt:
    packages:
      - python3
      - php5-cli
      - mono-devel
      - mono-mcs
      - nodejs

before_install:
  - source hxml/haxe_travis_scripts/scripts.sh

install:
  - install_hxcpp
  - install_hxjava
  - install_hxcs
  - haxelib install utest
  - haxelib list
  #- install_flashplayer

script:
  - haxe hxml/cpp.hxml -D travis && ./bin/cpp/TestAll
  - haxe hxml/cs.hxml -D travis && mono bin/cs/bin/TestAll.exe
  #- haxe hxml/flash.hxml -D travis -D exit && run_flash bin/flash.swf
  - haxe hxml/java.hxml -D travis && java -jar bin/java/TestAll.jar
  - haxe hxml/js.hxml -D travis && node bin/js.js && phantomjs bin/js.js
  - haxe hxml/php.hxml -D travis && php bin/php/index.php
  - haxe hxml/neko.hxml -D travis && neko bin/neko.n
  - haxe hxml/python.hxml -D travis && python3 bin/python.py
